services:
  db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
      POSTGRES_DB: notesdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - notes-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notesuser -d notesdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    container_name: app
    build: ./app
    image: app:${TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://notesuser:notespass@db:5432/notesdb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notes-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - notes-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
    networks:
      - notes-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - notes-net

volumes:
  pg_data:
  pgadmin_data:


networks:
  notes-net:
    driver: bridge
